nodes:
- address: 1.1.1.1
  user: ubuntu
  role:
  - controlplane
  - etcd
  port: 2233
  docker_socket: /var/run/docker.sock
- address: 2.2.2.2
  user: ubuntu
  role:
  - worker
  ssh_key_path: /home/user/.ssh/id_rsa
  ssh_key: |-
    -----BEGIN RSA PRIVATE KEY-----

    -----END RSA PRIVATE KEY-----
  ssh_cert_path: /home/user/.ssh/test-key-cert.pub
  ssh_cert: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3Bl....
- address: example.com
  user: ubuntu
  role:
  - worker
  hostname_override: node3
  internal_address: 192.168.1.7
  labels:
    app: ingress
  taints:
  - key: test-key
    value: test-value
    effect: NoSchedule
system_images:
  kubernetes: rancher/hyperkube:v1.10.3-rancher2
  etcd: rancher/coreos-etcd:v3.1.13
  alpine: rancher/rke-tools:v0.1.9
  nginx_proxy: rancher/rke-tools:v0.1.9
  cert_downloader: rancher/rke-tools:v0.1.9
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.9
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  pod_infra_container: rancher/pause-amd64:3.1
